# This is a basic workflow to help you get started with Actions

name: ChangeVelocityTest

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-dev:
    name: DeployDev
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Dev Deployed!
    
  deploy-preprod:
    name: DeployPreprod
      needs:deploy-dev
    runs-on: ubuntu-latest
    steps:     
       - uses: actions/checkout@v4

      # Runs a single command using the runners shell
       - name: Run a preprod script
         run: echo Preprod Deployed!

  snow-approval:
  # jobs that must complete successfully before this job will run
    needs: deploy-preprod
  # type of machine to run the job on
    runs-on: ubuntu-latest
    name: ServiceNow DevOps Change
    steps:
      - name: ServiceNow Change
        uses: ServiceNow/servicenow-devops-change@v4.0.0
        with:
        # Devops Integration Token
          devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
          devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
        # ServiceNow Instance URL
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
        # Orchestration Tool Id
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
        # GitHub Context
          context-github: ${{ toJSON(github) }}
        # Display Name of the Job
          job-name: 'ServiceNow DevOps Change'
          change-request: |
              {
                "setCloseCode" : true,
                "autoCloseChange" : true,
                "attributes": {
                  "requested_by": {
                     "name":"Andrzej Pawlus"
                  },
                 "start_date":"2024-09-12 14:00:00",
                 "end_date":"2024-09-12 14:30:00"
                }
              }
              
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a prod script
        run: echo Prod Deployed!

         
