# This is a basic workflow to help you get started with Actions

name: ChangeVelocityTest

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-dev:
    name: DeployDev
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Dev Deployed!
    
  deploy-preprod:
    name: DeployPreprod
      needs:deploy-dev
    runs-on: ubuntu-latest
    steps:     
       - uses: actions/checkout@v4

      # Runs a single command using the runners shell
       - name: Run a preprod script
         run: echo Preprod Deployed!

  snow-approval:
    name: SnowApproval
      needs:deploy-dev
    runs-on: ubuntu-latest
    steps:     
       - uses: actions/checkout@v4

      # Runs a single command using the runners shell
       - name: Run a preprod script
         run: echo Snow!

  deploy-prod:
    name: DeployProd
      needs:snow-approval
    runs-on: ubuntu-latest
    steps:     
       - uses: actions/checkout@v4

      # Runs a single command using the runners shell
       - name: Run a prod script
         run: echo Prod Deployed!

         
